# Data analysis

data/dataset1/dataset1.csv data/dataset2/dataset2.csv: src/data-preparation/download_data.R 
	Rscript src/data-preparation/download_data.R 

crime-rate-and-Airbnb/src/analysis: analysis_airbnb_data.R 
	R -vanilla < analysis_airbnb_data.R
	
